version: '3'
services:
  proxy:
    image: stream-conductor
    restart: always
    ports:
      - 5000:5000
      - 9000-9009:9000-9009
    links:
      - backendssh
    environment:
      - PORT_RANGE=9000-9009

  backendssh:
    image: macropin/sshd
    restart: always
    environment:
      - SSH_USERS=willem:10000:10000